const options = function getOptions() {
  return [
    {id: 0, value: "Malawi"},
    {id: 1, value: "Comoros"},
    {id: 2, value: "China"},
    {id: 3, value: "Netherlands Antilles"},
    {id: 4, value: "Congo, Republic of"},
    {id: 5, value: "Honduras"},
    {id: 6, value: "Israel"},
    {id: 7, value: "Cyprus"},
    {id: 8, value: "Cambodia"},
    {id: 9, value: "Russian Federation"},
    {id: 10, value: "Pakistan"},
    {id: 11, value: "France"},
    {id: 12, value: "Kiribati"},
    {id: 13, value: "Montserrat"},
    {id: 14, value: "Botswana"},
    {id: 15, value: "Croatia"},
    {id: 16, value: "Venezuela"},
    {id: 17, value: "French Polynesia"},
    {id: 18, value: "Tanzania"},
    {id: 19, value: "San Marino"},
    {id: 20, value: "East Timor"},
    {id: 21, value: "Tonga"},
    {id: 22, value: "Equatorial Guinea"},
    {id: 23, value: "Uzbekistan"},
    {id: 24, value: "Vanuatu"},
    {id: 25, value: "Anguilla"},
    {id: 26, value: "Sudan"},
    {id: 27, value: "Egypt"},
    {id: 28, value: "Tunisia"},
    {id: 29, value: "Bolivia"},
    {id: 30, value: "Turkmenistan"},
    {id: 31, value: "Brunei Darussalam"},
    {id: 32, value: "Jamaica"},
    {id: 33, value: "Georgia"},
    {id: 34, value: "Burkina Faso"},
    {id: 35, value: "Papua New Guinea"},
    {id: 36, value: "Kuwait"},
    {id: 37, value: "Tuvalu"},
    {id: 38, value: "Maldives"},
    {id: 39, value: "Mauritius"},
    {id: 40, value: "Mongolia"},
    {id: 41, value: "Saint Kitts and Nevis"},
    {id: 42, value: "Kazakhstan"},
    {id: 43, value: "Macedonia, Rep. of"},
    {id: 44, value: "Tibet"},
    {id: 45, value: "Virgin Islands (British)"},
    {id: 46, value: "Bahamas"},
    {id: 47, value: "Estonia"},
    {id: 48, value: "Lebanon"},
    {id: 49, value: "Yemen"},
    {id: 50, value: "Guinea-Bissau"},
    {id: 51, value: "Saint Vincent and the Grenadines"},
    {id: 52, value: "Mexico"},
    {id: 53, value: "Belize"},
    {id: 54, value: "Solomon Islands"},
    {id: 55, value: "Taiwan"},
    {id: 56, value: "South Africa"},
    {id: 57, value: "Belarus"},
    {id: 58, value: "Niger"},
    {id: 59, value: "Saudi Arabia"},
    {id: 60, value: "Pitcairn Island"},
    {id: 61, value: "Uganda"},
    {id: 62, value: "Serbia"},
    {id: 63, value: "Antigua and Barbuda"},
    {id: 64, value: "Armenia"},
    {id: 65, value: "Liechtenstein"},
    {id: 66, value: "Azerbaijan"},
    {id: 67, value: "Hungary"},
    {id: 68, value: "Nepal"},
    {id: 69, value: "New Zealand"},
    {id: 70, value: "Switzerland"},
    {id: 71, value: "Bangladesh"},
    {id: 72, value: "Liberia"},
    {id: 73, value: "Korea, Republic of (South Korea)"},
    {id: 74, value: "United Arab Emirates"},
    {id: 75, value: "Mozambique"},
    {id: 76, value: "Australia"},
    {id: 77, value: "Algeria"},
    {id: 78, value: "Sierra Leone"},
    {id: 79, value: "Guadeloupe"},
    {id: 80, value: "Bermuda"},
    {id: 81, value: "Spain"},
    {id: 82, value: "Slovakia (Slovak Republic)"},
    {id: 83, value: "Dominica"},
    {id: 84, value: "United States"},
    {id: 85, value: "Denmark"},
    {id: 86, value: "Great Britain"},
    {id: 87, value: "Martinique"},
    {id: 88, value: "Andorra"},
    {id: 89, value: "Greenland"},
    {id: 90, value: "Swaziland"},
    {id: 91, value: "Lao, People's Democratic Republic"},
    {id: 92, value: "Luxembourg"},
    {id: 93, value: "Zambia"},
    {id: 94, value: "Norway"},
    {id: 95, value: "Moldova, Republic of"},
    {id: 96, value: "Iraq"},
    {id: 97, value: "Namibia"},
    {id: 98, value: "Togo"},
    {id: 99, value: "Gabon"},
    {id: 100, value: "Iceland"},
    {id: 101, value: "Indonesia"},
    {id: 102, value: "Guatemala"},
    {id: 103, value: "Afghanistan"},
    {id: 104, value: "Canada"},
    {id: 105, value: "Jordan"},
    {id: 106, value: "Peru"},
    {id: 107, value: "Costa Rica"},
    {id: 108, value: "Fiji"},
    {id: 109, value: "Oman"},
    {id: 110, value: "Palestinian territories"},
    {id: 111, value: "Malta"},
    {id: 112, value: "Portugal"},
    {id: 113, value: "Ghana"},
    {id: 114, value: "Haiti"},
    {id: 115, value: "Reunion Island"},
    {id: 116, value: "Chad"},
    {id: 117, value: "Qatar"}
  ]
}()
