const options = function getOptions() {
  return [
    {id: 0, value: "Malawi"},
    {id: 1, value: "Comoros"},
    {id: 2, value: "China"},
    {id: 3, value: "Netherlands Antilles"},
    {id: 4, value: "Congo, Republic of"},
    {id: 5, value: "Honduras"},
    {id: 6, value: "Israel"},
    {id: 7, value: "Cyprus"},
    {id: 8, value: "Cambodia"},
    {id: 9, value: "Russian Federation"},
    {id: 10, value: "Pakistan"},
    {id: 11, value: "France"},
    {id: 12, value: "Kiribati"},
    {id: 13, value: "Montserrat"},
    {id: 14, value: "Botswana"},
    {id: 15, value: "Croatia"},
    {id: 16, value: "Venezuela"},
    {id: 17, value: "French Polynesia"},
    {id: 18, value: "Tanzania"},
    {id: 19, value: "San Marino"},
    {id: 20, value: "East Timor"},
    {id: 21, value: "Tonga"},
    {id: 22, value: "Equatorial Guinea"},
    {id: 23, value: "Uzbekistan"},
    {id: 24, value: "Vanuatu"},
    {id: 25, value: "Anguilla"},
    {id: 26, value: "Sudan"},
    {id: 27, value: "Egypt"},
    {id: 28, value: "Tunisia"},
    {id: 29, value: "Bolivia"},
    {id: 30, value: "Turkmenistan"},
    {id: 31, value: "Brunei Darussalam"},
    {id: 32, value: "Jamaica"},
    {id: 33, value: "Georgia"},
    {id: 34, value: "Burkina Faso"},
    {id: 35, value: "Papua New Guinea"},
    {id: 36, value: "Kuwait"},
    {id: 37, value: "Tuvalu"},
    {id: 38, value: "Maldives"},
    {id: 39, value: "Mauritius"},
    {id: 40, value: "Mongolia"},
    {id: 41, value: "Saint Kitts and Nevis"},
    {id: 42, value: "Kazakhstan"},
    {id: 43, value: "Macedonia, Rep. of"},
    {id: 44, value: "Tibet"},
    {id: 45, value: "Virgin Islands (British)"},
    {id: 46, value: "Bahamas"},
    {id: 47, value: "Estonia"},
    {id: 48, value: "Lebanon"},
    {id: 49, value: "Yemen"},
    {id: 50, value: "Guinea-Bissau"},
    {id: 51, value: "Saint Vincent and the Grenadines"},
    {id: 52, value: "Mexico"},
    {id: 53, value: "Belize"},
    {id: 54, value: "Solomon Islands"},
    {id: 55, value: "Taiwan"},
    {id: 56, value: "South Africa"},
    {id: 57, value: "Belarus"},
    {id: 58, value: "Niger"},
    {id: 59, value: "Saudi Arabia"},
    {id: 60, value: "Pitcairn Island"},
    {id: 61, value: "Uganda"},
    {id: 62, value: "Serbia"},
    {id: 63, value: "Antigua and Barbuda"},
    {id: 64, value: "Armenia"},
    {id: 65, value: "Liechtenstein"},
    {id: 66, value: "Azerbaijan"},
    {id: 67, value: "Hungary"},
    {id: 68, value: "Nepal"},
    {id: 69, value: "New Zealand"},
    {id: 70, value: "Switzerland"},
    {id: 71, value: "Bangladesh"},
    {id: 72, value: "Liberia"},
    {id: 73, value: "Korea, Republic of (South Korea)"},
    {id: 74, value: "United Arab Emirates"},
    {id: 75, value: "Mozambique"},
    {id: 76, value: "Australia"},
    {id: 77, value: "Algeria"},
    {id: 78, value: "Sierra Leone"},
    {id: 79, value: "Guadeloupe"},
    {id: 80, value: "Bermuda"},
    {id: 81, value: "Spain"},
    {id: 82, value: "Slovakia (Slovak Republic)"},
    {id: 83, value: "Dominica"},
    {id: 84, value: "United States"},
    {id: 85, value: "Denmark"},
    {id: 86, value: "Great Britain"},
    {id: 87, value: "Martinique"},
    {id: 88, value: "Andorra"},
    {id: 89, value: "Greenland"},
    {id: 90, value: "Swaziland"},
    {id: 91, value: "Lao, People's Democratic Republic"},
    {id: 92, value: "Luxembourg"},
    {id: 93, value: "Zambia"},
    {id: 94, value: "Norway"},
    {id: 95, value: "Moldova, Republic of"},
    {id: 96, value: "Iraq"},
    {id: 97, value: "Namibia"},
    {id: 98, value: "Togo"},
    {id: 99, value: "Gabon"},
    {id: 100, value: "Iceland"},
    {id: 101, value: "Indonesia"},
    {id: 102, value: "Guatemala"},
    {id: 103, value: "Afghanistan"},
    {id: 104, value: "Canada"},
    {id: 105, value: "Jordan"},
    {id: 106, value: "Peru"},
    {id: 107, value: "Costa Rica"},
    {id: 108, value: "Fiji"},
    {id: 109, value: "Oman"},
    {id: 110, value: "Palestinian territories"},
    {id: 111, value: "Malta"},
    {id: 112, value: "Portugal"},
    {id: 113, value: "Ghana"},
    {id: 114, value: "Haiti"},
    {id: 115, value: "Reunion Island"},
    {id: 116, value: "Chad"},
    {id: 117, value: "Qatar"},
    {id: 117, value: "Wolfsrealm"},
    {id: 118, value: "Embertown"},
    {id: 119, value: "Millstone"},
    {id: 120, value: "Seameet"},
    {id: 121, value: "Easthaven"},
    {id: 122, value: "Leeside"},
    {id: 123, value: "Lamorra"},
    {id: 124, value: "Sundance"},
    {id: 125, value: "Merriwich"},
    {id: 126, value: "Lochley"},
    {id: 127, value: "Wintervale"},
    {id: 128, value: "Snake’s Canyon"},
    {id: 129, value: "Frostfangs"},
    {id: 130, value: "Pineland"},
    {id: 131, value: "Aramoor"},
    {id: 132, value: "Ekaia"},
    {id: 133, value: "Nandungorteb"},
    {id: 134, value: "Glaskerville"},
    {id: 135, value: "Iron Hills"},
    {id: 136, value: "Pinnella Pass"},
    {id: 137, value: "Carran"},
    {id: 138, value: "Azmar"},
    {id: 139, value: "Windrip"},
    {id: 140, value: "Goldcrest"},
    {id: 141, value: "Harlen"},
    {id: 142, value: "Far Water"},
    {id: 143, value: "Aquarin"},
    {id: 144, value: "Amram"},
    {id: 145, value: "Wolfden"},
    {id: 146, value: "Broken Shield"},
    {id: 147, value: "Ozryn"},
    {id: 148, value: "Fangorn"},
    {id: 149, value: "Rhuin"},
    {id: 150, value: "Pella’s Wish"},
    {id: 151, value: "Marren’s Eve"},
    {id: 152, value: "Briar Glen"},
    {id: 153, value: "Erast"},
    {id: 154, value: "Jarren’s Outpost"},
    {id: 155, value: "Irragin"},
    {id: 156, value: "Anfauglith"},
    {id: 157, value: "Zao Ying"},
    {id: 158, value: "Strong Oak"},
    {id: 159, value: "Crow’s Cry"},
    {id: 160, value: "Hogsfeet"},
    {id: 161, value: "Ered"},
    {id: 162, value: "City of Fire"},
    {id: 163, value: "Bruinen"},
    {id: 164, value: "Avaglade"},
    {id: 165, value: "Legolin"},
    {id: 166, value: "Linesse"},
    {id: 167, value: "Oakensword"},
    {id: 168, value: "Stone’s Throw"},
    {id: 169, value: "Mahalaga"},
    {id: 170, value: "Shiny Ship"},
    {id: 171, value: "Bay of Balar"},
    {id: 172, value: "Nearon"},
    {id: 173, value: "Aerilon"},
    {id: 174, value: "Yarrin"},
    {id: 175, value: "Firecrow"},
    {id: 176, value: "Northtown"},
    {id: 177, value: "Brickelwhyte"},
    {id: 178, value: "Lullin"},
    {id: 179, value: "Snowforge"},
    {id: 180, value: "Ethermoor"},
    {id: 181, value: "Yi Ti"},
    {id: 182, value: "The Last Battle"},
    {id: 183, value: "Ship’s Haven"},
    {id: 184, value: "Stonewatch"},
    {id: 185, value: "Trudid"},
    {id: 186, value: "Dry Gulch"},
    {id: 187, value: "Rivermouth"},
    {id: 188, value: "Nogrod"},
    {id: 189, value: "Icemeet"},
    {id: 190, value: "Eredluin"},
    {id: 191, value: "Camorrus"},
    {id: 192, value: "Eastwatch"},
    {id: 193, value: "Oar’s Rest"},
    {id: 194, value: "Battlecliff"},
    {id: 195, value: "Greenloft"},
    {id: 196, value: "Widow’s Peak"},
    {id: 197, value: "Nuxvar"},
    {id: 198, value: "Three Streams"},
    {id: 199, value: "Westend"},
    {id: 200, value: "Rhaunar"},
    {id: 201, value: "Dimbar"},
    {id: 202, value: "Aenor’s Hill"},
    {id: 203, value: "Frostford"},
    {id: 204, value: "Death’s Door"},
    {id: 205, value: "East Armistice"},
    {id: 206, value: "Cullfield"},
    {id: 207, value: "Whiterun"},
    {id: 208, value: "Duarudelf"},
    {id: 209, value: "Xynnar"},
    {id: 210, value: "Knife’s Edge"},
    {id: 211, value: "Dorlomin"},
    {id: 212, value: "Silverkeep"},
    {id: 213, value: "Lakestown"},
    {id: 214, value: "Dragon’s Coast"},
    {id: 215, value: "Darendale"},
    {id: 216, value: "Eribourne"},
    {id: 217, value: "Pony Run"},
    {id: 218, value: "Ula’ree"},
    {id: 219, value: "Ashdrift"},
    {id: 220, value: "Jongvale"},
    {id: 221, value: "Zeffari"},
    {id: 222, value: "Wellspring"},
    {id: 223, value: "Eastford"},
    {id: 224, value: "Violl’s Garden"},
    {id: 225, value: "Northstead"},
    {id: 226, value: "Corralis"},
    {id: 227, value: "Nargorthon"},
    {id: 228, value: "Darkwell"},
    {id: 229, value: "South Warren"},
    {id: 230, value: "Shadestown"},
    {id: 231, value: "Doveshire"},
    {id: 232, value: "Pavv"},
    {id: 233, value: "Lakeshore"},
    {id: 234, value: "Harsengaard"},
    {id: 235, value: "Hwen"},
    {id: 236, value: "Willowdale"},
    {id: 237, value: "Pran"},
    {id: 238, value: "Ramshorn"},
    {id: 239, value: "Oakheart"},
    {id: 240, value: "Hollyhead"},
    {id: 241, value: "Garen’s Well"},
    {id: 242, value: "Whiteridge"},
    {id: 243, value: "Last Lock"},
    {id: 244, value: "Begger’s Hole"},
    {id: 245, value: "Brilthor"},
    {id: 246, value: "Doonatel"},
    {id: 247, value: "Tarrin"},
    {id: 248, value: "Zumka"},
    {id: 249, value: "Adurant"},
    {id: 250, value: "Freevale"},
    {id: 251, value: "Duskendale"},
    {id: 252, value: "Taur-in-duinath"},
    {id: 253, value: "Suilwen"},
    {id: 254, value: "Greenflower"},
    {id: 255, value: "Vertrock"},
    {id: 256, value: "Eden’s Gulf"},
    {id: 257, value: "Maglor’s Gap"},
    {id: 258, value: "Xan’s Bequest"},
    {id: 259, value: "Snowmelt"},
    {id: 260, value: "Moonbright"},
    {id: 261, value: "Veritas"},
    {id: 262, value: "Valley of Dusk"},
    {id: 263, value: "Kara’s Vale"},
    {id: 264, value: "Blue Field"},
    {id: 265, value: "Boatwright"},
    {id: 266, value: "Queenstown"},
    {id: 267, value: "Dorthonion"},
    {id: 268, value: "Doriath"},
    {id: 269, value: "Swordbreak"},
    {id: 270, value: "Arnor"},
    {id: 271, value: "Hull"},
    {id: 272, value: "Coalfell"},
    {id: 273, value: "Gulltown"},
    {id: 274, value: "The Gale"},
    {id: 275, value: "New Cresthill"},
    {id: 276, value: "Arrendyll"},
    {id: 277, value: "Wintergale"},
    {id: 278, value: "Arlan’s Way"},
    {id: 279, value: "Hillfar"},
    {id: 280, value: "Fool’s March"},
    {id: 281, value: "Orrinshire"},
    {id: 282, value: "Fallenedge"},
    {id: 283, value: "Vale of Doom"},
    {id: 284, value: "Elbright"},
    {id: 285, value: "Saker Keep"},
    {id: 286, value: "Doveseal"},
    {id: 287, value: "Pyreacre"},
    {id: 288, value: "Yellowseed"},
    {id: 289, value: "Rhudaur"},
    {id: 290, value: "Firebend"},
    {id: 291, value: "Northpass"},
    {id: 292, value: "Bullmar"},
    {id: 293, value: "Horizon’s End"},
    {id: 294, value: "Quan Ma"},
    {id: 295, value: "Mountmend"},
    {id: 296, value: "Beleriand"},
    {id: 297, value: "Ironforge"},
    {id: 298, value: "Ubbin Falls"},
    {id: 299, value: "Deathfall"},
    {id: 300, value: "Thales"},
    {id: 301, value: "Westwend"},
    {id: 302, value: "End’s Run"},
    {id: 303, value: "Greenglade"},
    {id: 304, value: "Goldenleaf"},
    {id: 305, value: "Black Hollow"},
    {id: 306, value: "Squall’s End"},
    {id: 307, value: "Riverwind"},
    {id: 308, value: "Southern Vale"},
    {id: 309, value: "Frostenvale"},
    {id: 310, value: "Eldarmar"},
    {id: 311, value: "Red Hawk"},
    {id: 312, value: "Haran"},
    {id: 313, value: "Old Ashton"},
    {id: 314, value: "Lothlann"},
    {id: 315, value: "Erede"},
    {id: 316, value: "Ecrin"},
    {id: 317, value: "I am rich or pool"},
    {id: 318, value: "Iamrichorpoool"}
  ]
}()
